version: '3.8'

services:
  spotify-mp3-sync:
    build:
      context: .
    environment:
      - DOTENV=true  # Ensures the .env is recognized
    volumes:
      - ./spotdl.config.json:/root/.spotdl/config.json
      - ${OUTPUT_PATH}:/app/music
      - ./.env:/app/.env
    command: python main.py  # Replace with your script's entry point
