version: '3.8'

services:
  spotify-mp3-sync:
    build:
      context: .
    environment:
      - DOTENV=true  # Ensures the .env is recognized
    env_files:
      - path: ./.env
      - path: ../music.env
    volumes:
      - ./spotdl.config.json:/root/.spotdl/config.json
      - music:/app/music
      - ./.env:/app/.env
    command: python main.py  # Replace with your script's entry point
volume:
  music:
    driver: local
    driver_opts:
      type: none
      device: ${MUSIC_PATH}
      o: bind
