version: '3.8'

services:
  spotify-mp3-sync:
    build:
      context: .
    environment:
      - DOTENV=true  # Ensures the .env is recognized
    env_file:
      - path: ./.env
    volumes:
      - ./spotdl.config.json:/root/.spotdl/config.json
      - /home/mele/storage/music:/app/music
      - ./.env:/app/.env
    command: python main.py  # Replace with your script's entry point
